name: Publish Docker image

on:
  push: 
    branches: ["production", "development"]
  pull_request:
    branches: ["production", "development"]

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GITHUB }}

      - name: Get current timestamp for REACT_APP_LAST_UPDATE
        id: timestamp
        run: |
          echo "BUILD_DATE=$(TZ="America/Bogota" date '+%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV   
          echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: Build   Docker image
        run: |          
          docker build . --build-arg APP_ENV=${{ github.ref_name }} --build-arg BUILD_DATE=${{env.BUILD_DATE}}  -t ghcr.io/cris590/ordencompra-front-v2-${{ github.ref_name }}          
      - name : Push Docker image
        run: |
           docker push ghcr.io/cris590/ordencompra-front-v2-${{ github.ref_name }}

  deploy:
    needs: create-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass
      - name: SSH into server and deploy
        run: |
          sshpass -p ${{ secrets.AUTH_PASS }} ssh -o StrictHostKeyChecking=no ${{ secrets.AUTH_SERVER }} << EOF
            sh  /services/deploy.sh ${{ github.ref_name }}            
          EOF
